steps:
  # containerize application
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/webprotege
      - --build-arg=JAR_FILE=target/webprotege-1.0.0.jar
      - .

images:
  - 'gcr.io/$PROJECT_ID/webprotege'